"""
Test Quality & Mutation Coverage MCP Server
===============================================
Analyzes production classes for test quality gaps, prioritizes by business
risk, generates meaningful behavioral tests, and validates them with
mutation testing.

Philosophy:
  ┌─────────────────────────────────────────────────────────────────┐
  │                                                                 │
  │  THIS SERVER DOES NOT GENERATE TESTS TO HIT A NUMBER.          │
  │                                                                 │
  │  It generates tests that CATCH BUGS — measured by whether       │
  │  they kill mutants, not whether they execute lines.             │
  │                                                                 │
  │  Coverage is a TRAILING INDICATOR of test quality.              │
  │  Mutation score is a LEADING INDICATOR.                         │
  │                                                                 │
  │  A 60% mutation score with meaningful tests beats               │
  │  95% line coverage with assertion-free tests every time.        │
  │                                                                 │
  └─────────────────────────────────────────────────────────────────┘

What It Does:
  ┌────────────┐   ┌────────────┐   ┌────────────┐   ┌────────────┐
  │ 1. ANALYZE │──▶│ 2. PRIORIT │──▶│ 3. GENERATE│──▶│ 4. VALIDATE│
  │            │   │    -IZE    │   │            │   │            │
  │ Run PIT    │   │ Score by   │   │ Behavioral │   │ Re-run PIT │
  │ mutation   │   │ business   │   │ contract   │   │ on new     │
  │ testing    │   │ risk ×     │   │ tests with │   │ tests      │
  │            │   │ complexity │   │ meaningful  │   │            │
  │ Parse XML  │   │ × change   │   │ assertions │   │ Verify     │
  │ reports    │   │ frequency  │   │            │   │ mutants    │
  │            │   │            │   │ Not stubs  │   │ killed     │
  └────────────┘   └────────────┘   └────────────┘   └────────────┘
         │                                                   │
         ▼                                                   ▼
  ┌────────────┐                                    ┌────────────┐
  │ 5. REPORT  │                                    │ 6. GATE    │
  │            │                                    │            │
  │ Per-class  │                                    │ Block PR   │
  │ Per-team   │                                    │ if below   │
  │ Trend      │                                    │ threshold  │
  └────────────┘                                    └────────────┘

Mutation Testing via PIT (PITest):
  PIT modifies bytecode (mutants), runs tests, checks if tests fail.
  If a mutant SURVIVES → your tests miss that bug.
  If a mutant is KILLED → your tests catch that bug.

Configuration:
  ~/.mcp-migration-kb/test-quality/
  ├── config.json              ← Thresholds, risk weights, exclusions
  ├── pit-reports/             ← PIT XML reports (per run)
  ├── baselines/               ← Per-project mutation score baselines
  ├── generated-tests/         ← Tests generated by this server
  └── history/                 ← Trend data over time

Environment Variables:
    TEST_QUALITY_MUTATION_THRESHOLD=80         (target mutation score %)
    TEST_QUALITY_LINE_COVERAGE_THRESHOLD=70    (minimum line coverage %)
    TEST_QUALITY_RISK_WEIGHT_FINANCIAL=3       (weight for financial code)
    TEST_QUALITY_RISK_WEIGHT_STATE=2           (weight for state transitions)
    TEST_QUALITY_RISK_WEIGHT_INTEGRATION=2     (weight for integration points)

Requirements:
    pip install fastmcp pyyaml

    Project requirements:
    - Maven project with pitest-maven plugin configured
    - OR Gradle with pitest-gradle plugin
    - JDK 17+

Usage:
    python test_quality_mcp_server.py
"""

import json
import os
import re
import subprocess
import xml.etree.ElementTree as ET
from collections import defaultdict
from dataclasses import dataclass, field, asdict
from datetime import datetime
from pathlib import Path
from typing import Optional

from fastmcp import FastMCP

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Configuration
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

KB_DIR = os.path.expanduser("~/.mcp-migration-kb")
TQ_DIR = os.path.join(KB_DIR, "test-quality")
CONFIG_FILE = os.path.join(TQ_DIR, "config.json")
PIT_REPORTS_DIR = os.path.join(TQ_DIR, "pit-reports")
BASELINES_DIR = os.path.join(TQ_DIR, "baselines")
GENERATED_DIR = os.path.join(TQ_DIR, "generated-tests")
HISTORY_DIR = os.path.join(TQ_DIR, "history")

# Defaults (overridable via config.json or env vars)
DEFAULT_CONFIG = {
    # ── Quality Gates ──
    "mutation_score_threshold": int(os.environ.get("TEST_QUALITY_MUTATION_THRESHOLD", "80")),
    "line_coverage_threshold": int(os.environ.get("TEST_QUALITY_LINE_COVERAGE_THRESHOLD", "70")),
    "new_code_mutation_threshold": 90,  # Higher bar for new code

    # ── Risk Weights (for prioritization) ──
    "risk_weights": {
        "financial": int(os.environ.get("TEST_QUALITY_RISK_WEIGHT_FINANCIAL", "3")),
        "state_transition": int(os.environ.get("TEST_QUALITY_RISK_WEIGHT_STATE", "2")),
        "integration_point": int(os.environ.get("TEST_QUALITY_RISK_WEIGHT_INTEGRATION", "2")),
        "security": 3,
        "data_mutation": 2,
        "error_handling": 2,
        "conditional_logic": 1,
    },

    # ── Risk Indicators (patterns that increase priority) ──
    "financial_indicators": [
        "payment", "billing", "invoice", "price", "tax", "discount",
        "charge", "refund", "balance", "ledger", "account", "fee",
        "BigDecimal", "Money", "Currency",
    ],
    "state_indicators": [
        "status", "state", "workflow", "transition", "approve", "reject",
        "cancel", "complete", "submit", "publish", "archive",
    ],
    "security_indicators": [
        "auth", "security", "permission", "role", "token", "credential",
        "password", "encrypt", "decrypt", "validate", "authorize",
    ],

    # ── Exclusions ──
    "exclude_packages": [
        "*.dto.*", "*.model.*", "*.entity.*", "*.config.*",
        "*.exception.*", "*.constant.*", "*.enum.*",
    ],
    "exclude_classes": [
        "*Application", "*Config", "*Properties", "*Constants",
    ],
    "exclude_methods": [
        "toString", "hashCode", "equals", "getter", "setter",
    ],

    # ── Generation Settings ──
    "test_style": "junit5",
    "use_mockito": True,
    "use_assertj": True,
    "generate_boundary_tests": True,
    "generate_null_tests": True,
    "generate_exception_tests": True,
    "max_tests_per_method": 5,

    # ── PIT Configuration ──
    "pit_mutators": "STRONGER",       # DEFAULTS, STRONGER, ALL
    "pit_threads": 4,
    "pit_timeout_factor": 1.25,
    "pit_timeout_constant": 3000,
}

mcp = FastMCP("Test Quality & Mutation Coverage")


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Config Management
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━


def _load_config() -> dict:
    os.makedirs(TQ_DIR, exist_ok=True)
    if os.path.isfile(CONFIG_FILE):
        try:
            with open(CONFIG_FILE) as f:
                user_config = json.load(f)
            merged = {**DEFAULT_CONFIG, **user_config}
            return merged
        except Exception:
            pass
    return dict(DEFAULT_CONFIG)


def _save_config(config: dict):
    os.makedirs(TQ_DIR, exist_ok=True)
    with open(CONFIG_FILE, "w") as f:
        json.dump(config, f, indent=2)


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Data Models
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━


@dataclass
class MutationReport:
    """Parsed PIT mutation testing report for a single class."""
    class_fqcn: str
    source_file: str = ""
    total_mutants: int = 0
    killed: int = 0
    survived: int = 0
    no_coverage: int = 0
    timed_out: int = 0
    mutation_score: float = 0.0       # killed / (killed + survived) * 100
    line_coverage: float = 0.0
    methods: list[dict] = field(default_factory=list)
    surviving_mutants: list[dict] = field(default_factory=list)


@dataclass
class RiskScore:
    """Business risk assessment for a class."""
    class_fqcn: str
    overall_risk: float = 0.0
    risk_factors: list[dict] = field(default_factory=list)
    category: str = "LOW"             # LOW, MEDIUM, HIGH, CRITICAL


@dataclass
class TestGap:
    """A specific test gap — a method or branch that needs better tests."""
    class_fqcn: str
    method_name: str
    gap_type: str                     # SURVIVING_MUTANT, NO_COVERAGE, WEAK_ASSERTION
    description: str = ""
    mutant_type: str = ""             # CONDITIONALS_BOUNDARY, RETURN_VALUES, etc.
    line_number: int = 0
    risk_score: float = 0.0
    suggested_test: str = ""


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# PIT Report Parser
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━


def _parse_pit_xml_report(report_path: str) -> list[MutationReport]:
    """Parse PIT XML mutations report into structured data."""
    reports = {}

    try:
        tree = ET.parse(report_path)
        root = tree.getroot()
    except Exception as e:
        return []

    for mutation in root.findall(".//mutation"):
        detected = mutation.attrib.get("detected", "false") == "true"
        status = mutation.attrib.get("status", "NO_COVERAGE")
        clazz = mutation.findtext("mutatedClass", "")
        method = mutation.findtext("mutatedMethod", "")
        line = int(mutation.findtext("lineNumber", "0"))
        mutator = mutation.findtext("mutator", "")
        description = mutation.findtext("description", "")
        source_file = mutation.findtext("sourceFile", "")
        killing_test = mutation.findtext("killingTest", "")

        if clazz not in reports:
            reports[clazz] = MutationReport(class_fqcn=clazz, source_file=source_file)

        r = reports[clazz]
        r.total_mutants += 1

        if status == "KILLED":
            r.killed += 1
        elif status == "SURVIVED":
            r.survived += 1
            r.surviving_mutants.append({
                "method": method,
                "line": line,
                "mutator": _simplify_mutator(mutator),
                "description": description,
                "status": status,
            })
        elif status == "NO_COVERAGE":
            r.no_coverage += 1
            r.surviving_mutants.append({
                "method": method,
                "line": line,
                "mutator": _simplify_mutator(mutator),
                "description": description,
                "status": "NO_COVERAGE",
            })
        elif status == "TIMED_OUT":
            r.timed_out += 1

    # Compute scores
    for r in reports.values():
        denominator = r.killed + r.survived
        r.mutation_score = round((r.killed / denominator * 100) if denominator > 0 else 0.0, 1)
        total_coverable = r.total_mutants - r.timed_out
        r.line_coverage = round(
            ((r.killed + r.timed_out) / r.total_mutants * 100) if r.total_mutants > 0 else 0.0, 1
        )

        # Aggregate by method
        method_stats = defaultdict(lambda: {"killed": 0, "survived": 0, "no_coverage": 0})
        for mut in r.surviving_mutants:
            m = mut["method"]
            method_stats[m][mut["status"].lower().replace(" ", "_")] += 1

        r.methods = [
            {"method": m, **stats}
            for m, stats in method_stats.items()
        ]

    return list(reports.values())


def _simplify_mutator(mutator_fqcn: str) -> str:
    """Simplify PIT mutator names to readable form."""
    mapping = {
        "ConditionalsBoundaryMutator": "BOUNDARY (< → <=, > → >=)",
        "IncrementsMutator": "INCREMENT (++ → --, -- → ++)",
        "InvertNegsMutator": "NEGATE (- → +)",
        "MathMutator": "MATH (+→-, *→/, etc.)",
        "NegateConditionalsMutator": "NEGATE_COND (== → !=, < → >=)",
        "ReturnValsMutator": "RETURN_VALUE (return X → null/0/false)",
        "VoidMethodCallMutator": "VOID_CALL (remove void method call)",
        "EmptyObjectReturnValsMutator": "EMPTY_RETURN (return empty instead of value)",
        "FalseReturnValsMutator": "FALSE_RETURN (return false)",
        "TrueReturnValsMutator": "TRUE_RETURN (return true)",
        "NullReturnValsMutator": "NULL_RETURN (return null)",
        "PrimitiveReturnsMutator": "PRIMITIVE_RETURN (return 0)",
    }
    simple = mutator_fqcn.rsplit(".", 1)[-1] if "." in mutator_fqcn else mutator_fqcn
    return mapping.get(simple, simple)


def _find_pit_report(project_path: str) -> Optional[str]:
    """Find the most recent PIT mutations.xml in a project."""
    candidates = [
        os.path.join(project_path, "target", "pit-reports"),
        os.path.join(project_path, "build", "reports", "pitest"),
    ]
    for base in candidates:
        if not os.path.isdir(base):
            continue
        # PIT creates timestamped subdirectories
        subdirs = sorted(Path(base).iterdir(), reverse=True)
        for sd in subdirs:
            xml = sd / "mutations.xml"
            if xml.is_file():
                return str(xml)
    return None


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Risk Scoring
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━


def _score_class_risk(class_fqcn: str, source_path: str, config: dict) -> RiskScore:
    """Score a class by business risk based on its name, content, and patterns."""
    risk = RiskScore(class_fqcn=class_fqcn)
    weights = config.get("risk_weights", {})

    # Read source if available
    content = ""
    if source_path and os.path.isfile(source_path):
        try:
            content = Path(source_path).read_text(errors="ignore").lower()
        except Exception:
            pass

    fqcn_lower = class_fqcn.lower()
    searchable = fqcn_lower + " " + content

    # Financial risk
    financial_indicators = config.get("financial_indicators", [])
    fin_matches = [ind for ind in financial_indicators if ind.lower() in searchable]
    if fin_matches:
        w = weights.get("financial", 3)
        risk.risk_factors.append({
            "factor": "FINANCIAL",
            "weight": w,
            "indicators": fin_matches[:5],
            "reason": "Handles money, pricing, or financial calculations",
        })
        risk.overall_risk += w * len(fin_matches)

    # State transition risk
    state_indicators = config.get("state_indicators", [])
    state_matches = [ind for ind in state_indicators if ind.lower() in searchable]
    if state_matches:
        w = weights.get("state_transition", 2)
        risk.risk_factors.append({
            "factor": "STATE_TRANSITION",
            "weight": w,
            "indicators": state_matches[:5],
            "reason": "Manages state transitions or workflow",
        })
        risk.overall_risk += w * len(state_matches)

    # Security risk
    security_indicators = config.get("security_indicators", [])
    sec_matches = [ind for ind in security_indicators if ind.lower() in searchable]
    if sec_matches:
        w = weights.get("security", 3)
        risk.risk_factors.append({
            "factor": "SECURITY",
            "weight": w,
            "indicators": sec_matches[:5],
            "reason": "Handles authentication, authorization, or sensitive data",
        })
        risk.overall_risk += w * len(sec_matches)

    # Complexity indicators from code
    if content:
        # Conditional complexity
        conditionals = len(re.findall(r"\bif\b|\bswitch\b|\b\?\s*:", content))
        if conditionals > 5:
            w = weights.get("conditional_logic", 1)
            risk.risk_factors.append({
                "factor": "COMPLEX_CONDITIONALS",
                "weight": w,
                "count": conditionals,
                "reason": f"{conditionals} conditional branches — high bug potential",
            })
            risk.overall_risk += w * min(conditionals, 10)

        # Error handling
        try_blocks = len(re.findall(r"\btry\s*\{", content))
        if try_blocks > 2:
            w = weights.get("error_handling", 2)
            risk.risk_factors.append({
                "factor": "ERROR_HANDLING",
                "weight": w,
                "count": try_blocks,
                "reason": f"{try_blocks} try-catch blocks — error paths need testing",
            })
            risk.overall_risk += w * min(try_blocks, 5)

        # Data mutation (DB writes, external calls)
        mutations = len(re.findall(
            r"\b(save|update|delete|insert|persist|merge|remove|execute|send|publish)\b", content
        ))
        if mutations > 0:
            w = weights.get("data_mutation", 2)
            risk.risk_factors.append({
                "factor": "DATA_MUTATION",
                "weight": w,
                "count": mutations,
                "reason": f"{mutations} data-mutating operations",
            })
            risk.overall_risk += w * min(mutations, 8)

    # Categorize
    if risk.overall_risk >= 15:
        risk.category = "CRITICAL"
    elif risk.overall_risk >= 8:
        risk.category = "HIGH"
    elif risk.overall_risk >= 4:
        risk.category = "MEDIUM"
    else:
        risk.category = "LOW"

    risk.overall_risk = round(risk.overall_risk, 1)
    return risk


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Test Gap Analysis
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━


def _analyze_test_gaps(report: MutationReport, risk: RiskScore, config: dict) -> list[TestGap]:
    """Identify specific test gaps from surviving mutants."""
    gaps = []
    threshold = config.get("mutation_score_threshold", 80)

    for mutant in report.surviving_mutants:
        mutator = mutant.get("mutator", "")
        method = mutant.get("method", "")
        line = mutant.get("line", 0)
        status = mutant.get("status", "")

        # Skip excluded methods
        excluded = config.get("exclude_methods", [])
        if any(method.lower().startswith(e.lower()) for e in excluded):
            continue

        gap_type = "SURVIVING_MUTANT" if status == "SURVIVED" else "NO_COVERAGE"
        suggestion = _suggest_test_for_mutant(report.class_fqcn, method, mutator, line)

        gap = TestGap(
            class_fqcn=report.class_fqcn,
            method_name=method,
            gap_type=gap_type,
            description=f"{mutator} at line {line} in {method}()",
            mutant_type=mutator,
            line_number=line,
            risk_score=risk.overall_risk,
            suggested_test=suggestion,
        )
        gaps.append(gap)

    # Sort: highest risk first, then by gap type (NO_COVERAGE before SURVIVING)
    gaps.sort(key=lambda g: (-g.risk_score, g.gap_type, g.method_name))
    return gaps


def _suggest_test_for_mutant(class_fqcn: str, method: str, mutator: str, line: int) -> str:
    """Generate a test suggestion based on the surviving mutant type."""
    simple_class = class_fqcn.rsplit(".", 1)[-1]
    camel_method = method[0].upper() + method[1:] if method else "Method"

    suggestions = {
        "BOUNDARY": (
            f"Test {method}() with boundary values. The boundary mutation "
            f"(< → <=) survived at line {line}, meaning your test doesn't "
            f"distinguish between < and <=. Add a test with the exact "
            f"boundary value."
        ),
        "NEGATE_COND": (
            f"Test {method}() with both true and false conditions. "
            f"The negated conditional survived at line {line}, meaning "
            f"your test only covers one branch. Add a test for the "
            f"opposite condition."
        ),
        "RETURN_VALUE": (
            f"Assert the EXACT return value of {method}(). A return "
            f"value mutation survived at line {line} — your test calls "
            f"the method but doesn't verify what it returns."
        ),
        "NULL_RETURN": (
            f"Assert that {method}() does NOT return null. A null-return "
            f"mutation survived at line {line}."
        ),
        "VOID_CALL": (
            f"Verify the side effect of a void method call in {method}(). "
            f"PIT removed a void call at line {line} and no test detected it. "
            f"Use Mockito.verify() to check the interaction."
        ),
        "MATH": (
            f"Test {method}() with values that distinguish between "
            f"+, -, *, /. A math mutation survived at line {line}. "
            f"Use values where the operations produce different results "
            f"(avoid 0, 1, 2)."
        ),
        "EMPTY_RETURN": (
            f"Assert the content of the return value from {method}(), "
            f"not just that it's non-null. An empty-return mutation "
            f"survived at line {line}."
        ),
    }

    for key, msg in suggestions.items():
        if key in mutator:
            return msg

    return (
        f"Add a test for {method}() that detects the {mutator} mutation "
        f"at line {line}. The current tests don't catch this change."
    )


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Test Generation
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━


def _generate_test_class(
    class_fqcn: str,
    gaps: list[TestGap],
    source_path: str,
    config: dict,
) -> str:
    """Generate a meaningful test class targeting specific mutation gaps."""
    simple_class = class_fqcn.rsplit(".", 1)[-1]
    package = class_fqcn.rsplit(".", 1)[0] if "." in class_fqcn else ""
    use_assertj = config.get("use_assertj", True)
    use_mockito = config.get("use_mockito", True)
    max_per_method = config.get("max_tests_per_method", 5)

    # Read source for dependency analysis
    source_content = ""
    if source_path and os.path.isfile(source_path):
        try:
            source_content = Path(source_path).read_text(errors="ignore")
        except Exception:
            pass

    # Detect dependencies for mocking
    deps = []
    if source_content:
        for dep_match in re.finditer(
            r"private\s+final\s+([\w<>]+)\s+(\w+)\s*;", source_content
        ):
            dep_type = dep_match.group(1)
            dep_name = dep_match.group(2)
            if dep_type[0].isupper() and dep_type not in (
                "String", "Integer", "Long", "Boolean", "List", "Map", "Set",
                "Logger", "ObjectMapper",
            ):
                deps.append({"type": dep_type, "name": dep_name})

    # Build test class
    lines = []
    lines.append(f"package {package};\n" if package else "")
    lines.append("")

    # Imports
    lines.append("import org.junit.jupiter.api.BeforeEach;")
    lines.append("import org.junit.jupiter.api.Test;")
    lines.append("import org.junit.jupiter.api.DisplayName;")
    lines.append("import org.junit.jupiter.api.Nested;")
    lines.append("import org.junit.jupiter.params.ParameterizedTest;")
    lines.append("import org.junit.jupiter.params.provider.ValueSource;")
    lines.append("import org.junit.jupiter.params.provider.NullAndEmptySource;")

    if use_assertj:
        lines.append("import static org.assertj.core.api.Assertions.assertThat;")
        lines.append("import static org.assertj.core.api.Assertions.assertThatThrownBy;")
    else:
        lines.append("import static org.junit.jupiter.api.Assertions.*;")

    if use_mockito and deps:
        lines.append("import org.junit.jupiter.api.extension.ExtendWith;")
        lines.append("import org.mockito.InjectMocks;")
        lines.append("import org.mockito.Mock;")
        lines.append("import org.mockito.junit.jupiter.MockitoExtension;")
        lines.append("import static org.mockito.Mockito.*;")
        lines.append("import static org.mockito.ArgumentMatchers.*;")

    lines.append("")
    lines.append(f"/**")
    lines.append(f" * Mutation-driven tests for {simple_class}.")
    lines.append(f" *")
    lines.append(f" * Generated to kill {len(gaps)} surviving mutants.")
    lines.append(f" * Each test targets a specific mutation gap identified by PIT.")
    lines.append(f" *")
    lines.append(f" * @see {class_fqcn}")
    lines.append(f" */")

    if use_mockito and deps:
        lines.append(f"@ExtendWith(MockitoExtension.class)")
    lines.append(f"class {simple_class}MutationTest {{")
    lines.append("")

    # Mocks
    for dep in deps:
        lines.append(f"    @Mock")
        lines.append(f"    private {dep['type']} {dep['name']};")
        lines.append("")

    if use_mockito and deps:
        lines.append(f"    @InjectMocks")
    lines.append(f"    private {simple_class} underTest;")
    lines.append("")

    # Setup
    if not deps:
        lines.append("    @BeforeEach")
        lines.append("    void setUp() {")
        lines.append(f"        underTest = new {simple_class}();")
        lines.append("    }")
        lines.append("")

    # Group gaps by method
    by_method: dict[str, list[TestGap]] = defaultdict(list)
    for gap in gaps:
        by_method[gap.method_name].append(gap)

    for method_name, method_gaps in by_method.items():
        if method_name in ("<init>", "<clinit>"):
            continue

        display_method = method_name[0].upper() + method_name[1:]
        lines.append(f"    @Nested")
        lines.append(f'    @DisplayName("{method_name}()")')
        lines.append(f"    class {display_method}Tests {{")
        lines.append("")

        for i, gap in enumerate(method_gaps[:max_per_method]):
            test_name = _generate_test_name(gap, i)
            lines.append(f"        @Test")
            lines.append(f'        @DisplayName("{_escape_java_string(gap.description)}")')
            lines.append(f"        void {test_name}() {{")
            lines.append(f"            // Target: {gap.mutant_type} at line {gap.line_number}")
            lines.append(f"            // {gap.suggested_test[:100]}")
            lines.append(f"")
            lines.append(f"            // Arrange")
            lines.append(f"            // TODO: Set up test data that makes the mutation detectable")
            lines.append(f"")
            lines.append(f"            // Act")
            lines.append(f"            // var result = underTest.{method_name}(...);")
            lines.append(f"")
            lines.append(f"            // Assert — MUST verify the specific behavior affected by the mutant")

            # Generate assertion hints based on mutant type
            if "BOUNDARY" in gap.mutant_type:
                lines.append(f"            // Use EXACT boundary values: if code uses <, test with ==")
                lines.append(f"            // assertThat(result).isEqualTo(expectedBoundaryResult);")
            elif "RETURN_VALUE" in gap.mutant_type or "NULL_RETURN" in gap.mutant_type:
                lines.append(f"            // assertThat(result).isNotNull();")
                lines.append(f"            // assertThat(result).isEqualTo(expectedValue);")
            elif "VOID_CALL" in gap.mutant_type:
                lines.append(f"            // verify(mockDependency).expectedMethodCall(any());")
                lines.append(f"            // verify(mockDependency, times(1)).sideEffect(...);")
            elif "NEGATE_COND" in gap.mutant_type:
                lines.append(f"            // Test BOTH branches of the condition at line {gap.line_number}")
                lines.append(f"            // assertThat(resultForTrue).isNotEqualTo(resultForFalse);")
            elif "MATH" in gap.mutant_type:
                lines.append(f"            // Use values where +, -, *, / produce DIFFERENT results")
                lines.append(f"            // Avoid: 0, 1, 2 (too symmetric). Use: 3, 7, 13")
            else:
                lines.append(f"            // assertThat(result).satisfies(r -> {{ /* verify behavior */ }});")

            lines.append(f"        }}")
            lines.append("")

        lines.append(f"    }}")
        lines.append("")

    lines.append("}")
    return "\n".join(lines)


def _generate_test_name(gap: TestGap, index: int) -> str:
    """Generate a descriptive test method name."""
    method = gap.method_name
    mutant = gap.mutant_type.split("(")[0].strip()

    name_parts = [
        "should",
        "Detect",
        re.sub(r"[^a-zA-Z0-9]", "", mutant).title(),
        "MutationIn",
        method[0].upper() + method[1:] if method else "Method",
    ]
    if index > 0:
        name_parts.append(f"Case{index + 1}")
    name_parts.append(f"Line{gap.line_number}")

    return "".join(name_parts)


def _escape_java_string(s: str) -> str:
    """Escape a string for use in Java string literal."""
    return s.replace('"', '\\"').replace("\n", " ")[:120]


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# PIT Execution
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━


def _run_pit(project_path: str, target_class: str = "", config: dict = None) -> dict:
    """Execute PIT mutation testing."""
    config = config or _load_config()
    project_path = os.path.abspath(project_path)

    # Detect build tool
    mvnw = os.path.join(project_path, "mvnw")
    mvn = mvnw if os.path.isfile(mvnw) else "mvn"

    cmd = [
        mvn,
        "org.pitest:pitest-maven:mutationCoverage",
        f"-Dpit.mutators={config.get('pit_mutators', 'STRONGER')}",
        f"-Dpit.threads={config.get('pit_threads', 4)}",
        f"-Dpit.timeoutFactor={config.get('pit_timeout_factor', 1.25)}",
        f"-Dpit.timeoutConstant={config.get('pit_timeout_constant', 3000)}",
        "-Dpit.outputFormats=XML",
    ]

    if target_class:
        cmd.append(f"-Dpit.targetClasses={target_class}")

    env = os.environ.copy()
    java_home = os.environ.get("JAVA_HOME", "")
    if java_home:
        env["PATH"] = os.path.join(java_home, "bin") + os.pathsep + env.get("PATH", "")

    try:
        result = subprocess.run(
            cmd, cwd=project_path, capture_output=True, text=True,
            timeout=900, env=env,
        )
        return {
            "success": result.returncode == 0,
            "stdout": result.stdout[-3000:],
            "stderr": result.stderr[-2000:],
        }
    except subprocess.TimeoutExpired:
        return {"success": False, "stderr": "PIT timed out after 15 minutes"}
    except FileNotFoundError as e:
        return {"success": False, "stderr": str(e)}


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# History & Trending
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━


def _save_history(project_path: str, reports: list[MutationReport]):
    """Save a snapshot of mutation scores for trend tracking."""
    os.makedirs(HISTORY_DIR, exist_ok=True)
    project_name = os.path.basename(project_path)
    ts = datetime.now().strftime("%Y%m%d-%H%M%S")

    overall_killed = sum(r.killed for r in reports)
    overall_survived = sum(r.survived for r in reports)
    denom = overall_killed + overall_survived
    overall_score = round((overall_killed / denom * 100) if denom > 0 else 0, 1)

    entry = {
        "timestamp": datetime.now().isoformat(),
        "project": project_name,
        "overall_mutation_score": overall_score,
        "total_classes": len(reports),
        "total_mutants": sum(r.total_mutants for r in reports),
        "killed": overall_killed,
        "survived": overall_survived,
        "classes_below_threshold": len([
            r for r in reports
            if r.mutation_score < _load_config().get("mutation_score_threshold", 80)
        ]),
    }

    # Append to history file
    history_file = os.path.join(HISTORY_DIR, f"{project_name}.jsonl")
    with open(history_file, "a") as f:
        f.write(json.dumps(entry) + "\n")

    return entry


def _load_history(project_name: str, limit: int = 30) -> list[dict]:
    """Load mutation score history for trend analysis."""
    history_file = os.path.join(HISTORY_DIR, f"{project_name}.jsonl")
    if not os.path.isfile(history_file):
        return []

    entries = []
    try:
        with open(history_file) as f:
            for line in f:
                if line.strip():
                    entries.append(json.loads(line))
    except Exception:
        pass

    return entries[-limit:]


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# MCP Tools
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━


@mcp.tool()
def configure_quality_gates(
    mutation_threshold: int = 0,
    line_coverage_threshold: int = 0,
    new_code_threshold: int = 0,
    pit_mutators: str = "",
    exclude_packages: str = "",
) -> dict:
    """
    Configure test quality thresholds and exclusions.

    Args:
        mutation_threshold:      Target mutation score % (default 80)
        line_coverage_threshold: Minimum line coverage % (default 70)
        new_code_threshold:      Mutation threshold for new code (default 90)
        pit_mutators:            PIT mutator group: DEFAULTS, STRONGER, ALL
        exclude_packages:        Comma-separated package patterns to skip
    """
    config = _load_config()

    if mutation_threshold > 0:
        config["mutation_score_threshold"] = mutation_threshold
    if line_coverage_threshold > 0:
        config["line_coverage_threshold"] = line_coverage_threshold
    if new_code_threshold > 0:
        config["new_code_mutation_threshold"] = new_code_threshold
    if pit_mutators:
        config["pit_mutators"] = pit_mutators
    if exclude_packages:
        config["exclude_packages"] = [p.strip() for p in exclude_packages.split(",")]

    _save_config(config)
    return {"status": "configured", "config": config}


@mcp.tool()
def analyze_mutation_coverage(
    project_path: str,
    run_pit: bool = False,
    target_class: str = "",
) -> dict:
    """
    Analyze mutation testing results for a project.

    If run_pit=True, executes PIT first. Otherwise, parses the most
    recent PIT report from the project's target/build directory.

    Args:
        project_path:  Path to the Maven/Gradle project.
        run_pit:       Whether to run PIT first (takes minutes).
        target_class:  Specific class pattern to test (e.g., "com.company.order.*")

    Returns:
        Per-class mutation scores, risk assessment, and prioritized test gaps.
    """
    project_path = os.path.abspath(project_path)
    config = _load_config()

    # Run PIT if requested
    if run_pit:
        pit_result = _run_pit(project_path, target_class, config)
        if not pit_result["success"]:
            return {
                "error": "PIT execution failed",
                "details": pit_result.get("stderr", ""),
                "hint": "Ensure pitest-maven plugin is in pom.xml and tests compile.",
            }

    # Find and parse report
    report_path = _find_pit_report(project_path)
    if not report_path:
        return {
            "error": "No PIT report found.",
            "hint": "Run with run_pit=True, or execute PIT manually: mvn pitest:mutationCoverage",
        }

    reports = _parse_pit_xml_report(report_path)
    if not reports:
        return {"error": "PIT report was empty or unparsable."}

    # Filter exclusions
    excluded_pkgs = config.get("exclude_packages", [])
    filtered = []
    for r in reports:
        skip = False
        for pattern in excluded_pkgs:
            regex = pattern.replace(".", "\\.").replace("*", ".*")
            if re.match(regex, r.class_fqcn):
                skip = True
                break
        if not skip:
            filtered.append(r)

    threshold = config.get("mutation_score_threshold", 80)

    # Score risk for each class
    project_name = os.path.basename(project_path)
    class_results = []
    below_threshold = []

    for r in filtered:
        # Find source file
        source_path = ""
        simple_name = r.class_fqcn.rsplit(".", 1)[-1]
        for sf in Path(project_path).rglob(f"{simple_name}.java"):
            if "/test/" not in str(sf):
                source_path = str(sf)
                break

        risk = _score_class_risk(r.class_fqcn, source_path, config)
        gaps = _analyze_test_gaps(r, risk, config)

        entry = {
            "class": r.class_fqcn,
            "mutation_score": r.mutation_score,
            "killed": r.killed,
            "survived": r.survived,
            "no_coverage": r.no_coverage,
            "total_mutants": r.total_mutants,
            "meets_threshold": r.mutation_score >= threshold,
            "risk_category": risk.category,
            "risk_score": risk.overall_risk,
            "risk_factors": [f["factor"] for f in risk.risk_factors],
            "test_gaps": len(gaps),
            "top_gaps": [
                {"method": g.method_name, "type": g.mutant_type, "line": g.line_number}
                for g in gaps[:5]
            ],
        }
        class_results.append(entry)

        if r.mutation_score < threshold:
            below_threshold.append(entry)

    # Sort by priority: risk × gap size
    below_threshold.sort(
        key=lambda c: -(c["risk_score"] * c["test_gaps"]),
    )

    # Overall stats
    total_killed = sum(r.killed for r in filtered)
    total_survived = sum(r.survived for r in filtered)
    denom = total_killed + total_survived
    overall_score = round((total_killed / denom * 100) if denom > 0 else 0, 1)

    # Save history
    _save_history(project_path, filtered)

    return {
        "project": project_path,
        "pit_report": report_path,
        "overall_mutation_score": overall_score,
        "threshold": threshold,
        "meets_threshold": overall_score >= threshold,
        "total_classes": len(filtered),
        "classes_below_threshold": len(below_threshold),
        "summary": {
            "total_mutants": sum(r.total_mutants for r in filtered),
            "killed": total_killed,
            "survived": total_survived,
            "no_coverage": sum(r.no_coverage for r in filtered),
        },
        "priority_classes": below_threshold[:15],
        "all_classes": sorted(class_results, key=lambda c: c["mutation_score"]),
    }


@mcp.tool()
def generate_tests_for_gaps(
    project_path: str,
    class_fqcn: str = "",
    max_classes: int = 5,
    output_dir: str = "",
) -> dict:
    """
    Generate meaningful test classes targeting specific mutation gaps.

    Tests are generated to KILL SURVIVING MUTANTS, not to pad coverage.
    Each test method targets a specific mutant type with an appropriate
    assertion strategy.

    Args:
        project_path:  Project root (to find PIT report and source files)
        class_fqcn:    Specific class to generate tests for (empty = top priority)
        max_classes:    Maximum number of classes to generate tests for
        output_dir:     Where to write generated tests (default: project test dir)
    """
    project_path = os.path.abspath(project_path)
    config = _load_config()

    report_path = _find_pit_report(project_path)
    if not report_path:
        return {"error": "No PIT report found. Run analyze_mutation_coverage first."}

    reports = _parse_pit_xml_report(report_path)
    threshold = config.get("mutation_score_threshold", 80)

    # Select classes to generate tests for
    targets = []
    for r in reports:
        if class_fqcn and r.class_fqcn != class_fqcn:
            if not r.class_fqcn.endswith(f".{class_fqcn}"):
                continue
        if r.mutation_score >= threshold and not class_fqcn:
            continue
        if not r.surviving_mutants:
            continue

        source_path = ""
        simple_name = r.class_fqcn.rsplit(".", 1)[-1]
        for sf in Path(project_path).rglob(f"{simple_name}.java"):
            if "/test/" not in str(sf):
                source_path = str(sf)
                break

        risk = _score_class_risk(r.class_fqcn, source_path, config)
        gaps = _analyze_test_gaps(r, risk, config)

        targets.append({
            "report": r,
            "risk": risk,
            "gaps": gaps,
            "source_path": source_path,
            "priority": risk.overall_risk * len(gaps),
        })

    targets.sort(key=lambda t: -t["priority"])
    targets = targets[:max_classes]

    if not targets:
        return {"message": "No classes below threshold with surviving mutants."}

    # Determine output directory
    if not output_dir:
        # Standard Maven test directory
        output_dir = os.path.join(project_path, "src", "test", "java")

    generated_files = []
    for t in targets:
        report = t["report"]
        gaps = t["gaps"]
        source_path = t["source_path"]

        test_content = _generate_test_class(
            report.class_fqcn, gaps, source_path, config,
        )

        # Determine output path
        package_path = report.class_fqcn.rsplit(".", 1)[0].replace(".", os.sep) if "." in report.class_fqcn else ""
        simple_name = report.class_fqcn.rsplit(".", 1)[-1]
        test_file_name = f"{simple_name}MutationTest.java"
        test_dir = os.path.join(output_dir, package_path)
        os.makedirs(test_dir, exist_ok=True)
        test_file = os.path.join(test_dir, test_file_name)

        Path(test_file).write_text(test_content)

        generated_files.append({
            "class": report.class_fqcn,
            "file": test_file,
            "gaps_targeted": len(gaps),
            "risk": t["risk"].category,
            "current_mutation_score": report.mutation_score,
        })

    return {
        "generated": len(generated_files),
        "files": generated_files,
        "next_steps": [
            "1. Fill in the TODO sections with actual test logic",
            "2. Run tests: mvn test",
            "3. Re-run PIT: mvn pitest:mutationCoverage",
            "4. Verify mutation score improved: analyze_mutation_coverage()",
        ],
    }


@mcp.tool()
def mutation_score_trend(project_path: str) -> dict:
    """
    Show mutation score trend over time for a project.

    Returns historical data points for charting.
    """
    project_name = os.path.basename(os.path.abspath(project_path))
    history = _load_history(project_name)

    if not history:
        return {"message": f"No history for '{project_name}'. Run analyze_mutation_coverage first."}

    config = _load_config()
    threshold = config.get("mutation_score_threshold", 80)

    # Compute trend
    if len(history) >= 2:
        first = history[0]["overall_mutation_score"]
        latest = history[-1]["overall_mutation_score"]
        trend = round(latest - first, 1)
        trend_direction = "IMPROVING" if trend > 0 else "DECLINING" if trend < 0 else "STABLE"
    else:
        trend = 0
        trend_direction = "INSUFFICIENT_DATA"

    return {
        "project": project_name,
        "threshold": threshold,
        "data_points": len(history),
        "latest_score": history[-1]["overall_mutation_score"] if history else 0,
        "trend": trend,
        "trend_direction": trend_direction,
        "history": history,
    }


@mcp.tool()
def quality_gate_check(project_path: str) -> dict:
    """
    Run a quality gate check suitable for CI/CD pipelines.

    Returns PASS or FAIL with specific reasons.

    This is the tool to call from CI to decide if a PR should be blocked.
    """
    project_path = os.path.abspath(project_path)
    config = _load_config()

    report_path = _find_pit_report(project_path)
    if not report_path:
        return {
            "gate": "SKIP",
            "reason": "No PIT report found. Run PIT first.",
        }

    reports = _parse_pit_xml_report(report_path)
    threshold = config.get("mutation_score_threshold", 80)
    line_threshold = config.get("line_coverage_threshold", 70)

    total_killed = sum(r.killed for r in reports)
    total_survived = sum(r.survived for r in reports)
    denom = total_killed + total_survived
    overall_score = round((total_killed / denom * 100) if denom > 0 else 0, 1)

    failures = []

    # Gate 1: Overall mutation score
    if overall_score < threshold:
        failures.append({
            "gate": "MUTATION_SCORE",
            "actual": overall_score,
            "threshold": threshold,
            "message": f"Overall mutation score {overall_score}% is below {threshold}% threshold.",
        })

    # Gate 2: No class with zero coverage
    zero_coverage = [r for r in reports if r.no_coverage == r.total_mutants and r.total_mutants > 0]
    if zero_coverage:
        failures.append({
            "gate": "ZERO_COVERAGE_CLASSES",
            "count": len(zero_coverage),
            "classes": [r.class_fqcn for r in zero_coverage[:10]],
            "message": f"{len(zero_coverage)} classes have zero test coverage.",
        })

    # Gate 3: High-risk classes must be above threshold
    for r in reports:
        source_path = ""
        simple_name = r.class_fqcn.rsplit(".", 1)[-1]
        for sf in Path(project_path).rglob(f"{simple_name}.java"):
            if "/test/" not in str(sf):
                source_path = str(sf)
                break

        risk = _score_class_risk(r.class_fqcn, source_path, config)
        if risk.category in ("CRITICAL", "HIGH") and r.mutation_score < threshold:
            failures.append({
                "gate": "HIGH_RISK_UNDERTESTED",
                "class": r.class_fqcn,
                "risk": risk.category,
                "score": r.mutation_score,
                "threshold": threshold,
                "message": f"{risk.category}-risk class {r.class_fqcn} has {r.mutation_score}% mutation score.",
            })

    passed = len(failures) == 0

    return {
        "gate": "PASS" if passed else "FAIL",
        "overall_mutation_score": overall_score,
        "threshold": threshold,
        "total_classes": len(reports),
        "failures": failures,
    }


@mcp.tool()
def get_config() -> dict:
    """View current test quality configuration."""
    return _load_config()


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Resources
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━


@mcp.resource("test-quality://status")
def tq_status() -> str:
    config = _load_config()
    return (
        f"Test Quality & Mutation Coverage Server\n"
        f"{'=' * 40}\n"
        f"Mutation threshold: {config['mutation_score_threshold']}%\n"
        f"Line coverage threshold: {config['line_coverage_threshold']}%\n"
        f"PIT mutators: {config['pit_mutators']}\n"
        f"Storage: {TQ_DIR}\n"
    )


if __name__ == "__main__":
    mcp.run()
